### ISSUE TITLE
Request for guide/guidance for adding new Atlas / CoordinateSpace / Parcellation to openMINDS (specifically Marmoset)

### ISSUE THREAD

**Issue by baishi** [openMetadataInitiative/openMINDS#62]
Hi,

I'm tasked to investigate how to include our Marmoset atlas into the Siibra suit. I noticed there are multiple references to the OpenMinds/ParcellationEntities etc. So I wish to craft the needed metadata.

I searched around and didn't find a holistic document or step by step guide about this task.

My understanding is that to add a whole new set of Atlas / CoordinateSpace / Parcellation of a new Species, I need to craft the BrainAtlas, BrainAtlasVersion, commonCoordinateSpaces, commonCoordinateSpaceVersion, parcellationEntity, parcellationEntityVersion. So is there any script to ensure everything mandatory is populated and there is no typo etc or I need to copy an existing one as template and fill in accordingly?

Also I noticed there are overlapping attributes in say BrainAtlas and BrainAtlasVersions. So with the same attribute, does the BrainAtlas's value should be the value of the latest version? Is there any overriding happening in the resolving process?

When I get the metadata ready, do I create a PR for the files?

Best Regards,
Shi

**Comment by baishi** [comment]
Hi @Raphael-Gazzotti, any input please?

**Comment by apdavison** [comment]
Hi @baishi  - I don't think we have a step-by-step guide yet. We'll discuss this in our next developers' meeting and get back to you.

**Comment by UlrikeS91** [comment]
Hi @baishi,

@apdavison is correct. We do not have a step-by-step guide yet, but I can help you getting started. 

### 1. Overview
Since the Marmoset atlas does not exist in openMINDS yet, we will have to register all atlas elements for the atlas. These include:
1. brain atlas (with nested parcellation terminology)
2. brain atlas version (with nested parcellation terminology version)
3. common coordinate space
4. common coordinate space version (which is linked by one or multiple brain atlas version that used it)
5. parcellation entities (which make up the terminology across all versions of the atlas)
6. parcellation entity versions (which make up the specific terminology used within a specific version of the atlas; with nested information about the atlas annotations)

### 2. Version entities vs. version-independent entities
**Version-independent entities:** brain atlas (& parcellation terminology), common coordinate space, parcellation entity
**Version entities:** brain atlas version (& parcellation terminology version), common coordinate space version, parcellation entity version (& atlas annotation)  
As you noticed, there are several overlapping attributes between them. We typically register the same value for both unless there are any reasons for having something different (e.g., a new name and abbreviation is assigned to a parcellation entity version in the latest version which has a different name in the version before). Even though the value for the version entity could be inherited from the version-independent one, we try to be as explicit as possible (i.e., duplication is prefer for the openMINDS instances). The "versionIdentifier" specifically identifies the version and is combined with, e.g., abbreviation or short name to create specific identifiers for the different entities (e.g., WHSSDatlas vs. WHSSDatlas_v4). Here is an overview of relevant properties and how we typically handle them for integrating atlas-related instances into the openMINDS_instances repository:

| AtlasEntity(Version) | property | duplication? |
| -- | -- | -- |
| BrainAtlas(Version) | abbreviation | yes |
| BrainAtlas(Version) | description | yes ("versionInnovation" of version should be used to provide version specific descriptions) |
| BrainAtlas(Version) | digitalIdentifier | no; must be specific, leave blank if none exists |
| BrainAtlas(Version) | fullName | yes |
| BrainAtlas(Version) | homepage | yes/no; preferably specific, but one webpage may describe both |
| BrainAtlas(Version) | howToCite | typically specific or BrainAtlas has none |
| BrainAtlas(Version) | ontologyIdentifier | no; must be specific, leave blank if none exists |
| BrainAtlas(Version) | shortName | yes |
| CommonCoordinateSpace(Version) | abbreviation | yes |
| CommonCoordinateSpace(Version) | description | yes ("versionInnovation" of version should be used to provide version specific descriptions) |
| CommonCoordinateSpace(Version) | digitalIdentifier | no; must be specific, leave blank if none exists |
| CommonCoordinateSpace(Version) | fullName | yes |
| CommonCoordinateSpace(Version) | homepage | yes/no; preferably specific, but one webpage may describe both (or may be the same as for the BrainAtlas(Version) that used/created it) |
| CommonCoordinateSpace(Version) | howToCite | typically specific or CommonCoordinateSpace has none |
| CommonCoordinateSpace(Version) | ontologyIdentifier | no; must be specific, leave blank if none exists |
| CommonCoordinateSpace(Version) | shortName | yes |
| ParcellationEntity(Version) | abbreviation | reflects atlas documentation; ParcellationEntity typically corresponds to latest version if changes have been made between versions |
| ParcellationEntity(Version) | alternateName | reflects atlas documentation (i.e., if multiple names have been used for the same entity, these may be stated here); we have e.g., used it to add older versions of the name to reflect their relationship |
| ParcellationEntity(Version) | hasParent | can point to same entity, reflects atlas documentation |
| ParcellationEntity(Version) | lookupLabel | no; must be specific and name/abbreviation + atlas abbreviation + versionIdentifier |
| ParcellationEntity(Version) | name | reflects atlas documentation; often yes |
| ParcellationEntity(Version) | ontologyIdentifier | no; must be specific, leave blank if none exists |

For ParcellationEntity(Version) it is important to note that we only register delineated brain regions as ParcellationEntityVersions. Other regions used to create a hierarchy (i.e., the name assigned to a combination of several delineations) or that are included in the overall terminology but are not delineated yet are registered as ParcellationEntities.  

You may use existing atlas representations as template/inspiration but please be aware that atlas representations can vary a lot and that our collection is still a work in progress. The most complete representations are the Julich Brain Atlas (JBA) and Waxholm Space rat atlas (WHSSDatlas). 

### 3. Programmatic population
You can use one of our code packages to help you create the necessary JSON-LDs (e.g., https://github.com/openMetadataInitiative/openMINDS_python or https://github.com/openMetadataInitiative/openMINDS_matlab).

### 4. Integration into openMINDS
Yes, once you have created the necessary JSON-LDS, you can create a PR. Feel free to create a draft PR if you'd like my input on your work in progress. This way I review along the way and hel you reduce the amount of work to put into creating the atlas representation. 

Let me know if anything is unclear or if you need more information about something.

**Comment by UlrikeS91** [comment]
@apdavison , could you help @baishi with the openMINDS_python code package?

**Comment by apdavison** [comment]
Hi @baishi 

Before loading the collection, you need to import the relevant schemas, e.g.:
```
import openminds.latest as om
```

We're aware this is not intuitive, and plan to fix this in future (see [ticket here](https://github.com/openMetadataInitiative/openMINDS_Python/issues/49)).

You may also need to upgrade openMINDS Python to v0.3.0 (`pip install -U openminds`).

**Comment by baishi** [comment]
Hi @apdavison,

I'm trying to use this one to validate the metadata
```
import openminds.latest as om
pe = om.sands.ParcellationEntity()
pe.load('instances/latest/parcellationEntities/WHSSDatlas/WHSSDatlas_zonaIncertaDorsalPart.jsonld')
pe.validate()
defaultdict(list, {'required': ['name is required, but was not provided']})
```

But the file indeed has "name" attribute.

On the other hand
```
ba = om.sands.BrainAtlas()
ba.load('instances/latest/brainAtlases/WHSSDatlas.jsonld')
ba.validate()
defaultdict(list,
            {'required': ['authors is required, but was not provided',
              'description is required, but was not provided',
              'full_name is required, but was not provided',
              'has_terminology is required, but was not provided',
              'has_versions is required, but was not provided',
              'short_name is required, but was not provided']})
```
However, authors, description fullName, hasTerminology hasVersion are defined in the metadata file.

Is that a mismatch or something I used wrongly?

Best Regards,
Shi

**Comment by baishi** [comment]
Hi @apdavison 

It didn't work for me:
```
In [7]: import openminds

In [8]: print (openminds.__version__)
0.3.0

In [1]: import openminds.latest as om
In [3]: pe = om.sands.ParcellationEntity.load('instances/v3.0/terminologies/UBERONParcellation/cerebellarNuclearComplex.jsonld')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 pe = om.sands.ParcellationEntity.load('instances/v3.0/terminologies/UBERONParcellation/cerebellarNuclearComplex.jsonld')

File ~/miniconda3/envs/python3/lib/python3.10/site-packages/openminds/base.py:218, in LinkedMetadata.load(cls, file_path)
    216 with open(file_path, "r") as input_file:
    217     data = json.load(input_file)
--> 218 return cls.from_jsonld(data)

File ~/miniconda3/envs/python3/lib/python3.10/site-packages/openminds/base.py:112, in Node.from_jsonld(cls, data)
    110 type_ = data_copy.pop("@type")
    111 if type_ and type_ != cls.type_:
--> 112     raise TypeError(f"Mismatched types. Data has '{type_}' but trying to create '{cls.type_}'")
    113 deserialized_data = {}
    114 if issubclass(cls, LinkedMetadata):

TypeError: Mismatched types. Data has 'https://openminds.ebrains.eu/controlledTerms/UBERONParcellation' but trying to create 'https://openminds.om-i.org/types/ParcellationEntity'

In [4]: pe = om.sands.ParcellationEntity.load('instances/latest/parcellationEntities/WHSSDatlas/WHSSDatlas_zonaIncertaDorsalPart.jsonld')

In [5]: pe.validate()
Out[5]: 
defaultdict(list,
            {'type': ["has_versions: Expected ParcellationEntityVersion, value contains <class 'openminds.base.Link'>"]})
```

I ran the script against main/HEAD
```
commit 4b3f8206f5e70476ec345b6669cd463d544f2091 (HEAD -> main, origin/main, origin/HEAD)
Merge: 11bd7ab2 b50e012d
Author: Lyuba Zehl <lyuba.zehl@ebrains.eu>
Date:   Wed Apr 16 10:11:07 2025 +0200

    Merge pull request #263 from Raphael-Gazzotti/instance-validation
    
    Reusable validation workflow from openMINDS_actions.
```

**Comment by apdavison** [comment]
There are a few issues here:

1. You need to match the openMINDS version of the schemas and the instances. You were trying to load an instance from "instances/v3.0", which means you need version 3 of the schemas:

```python
import openminds.v3 as omv3

cnc = omv3.controlled_terms.UBERONParcellation.load('instances/v3.0/terminologies/UBERONParcellation/cerebellarNuclearComplex.jsonld')
```

2. You need to use the correct class for the instance (you were trying to load an UBERONParcellation instance using the ParcellationEntity class).

3. In your final example, the validation error is because "has_versions" contains just a link to another instance, so the validator cannot confirm the linked instance is of the correct type. For a full validation you would need to download all the linked instances and load everything at once into a Collection. To suppress this error, use `pe.validate(ignore=["type"])`

**Comment by lzehl** [comment]
@baishi just a small note from my side here before we hopefully meet for further discussions :) It is not enough for an instance to list the attribute with a null value to fulfill requirement. It actually has to provide a value. However, we are diverging a bit from openMINDS for atlases and common coordinate spaces in the openMINDS registration (to not collide with systems like EBRAINS and their registration, as for e.g. Persons). Fixing this is the required properties is on our TODO list for the next version. 

Moreover, there are other conventions from for controlled openMINDS instances that are not validated. For example: Underscore is used as a specific separator in atlas instances (between certain components in the atids). We do not allow this to be used to replace white spaces.

I'm looking forward to meeting you and discuss the Marmoset Nencki-Monash template :)

**Comment by lzehl** [comment]
@baishi since I cannot raise issues on your fork I will provide first feedback here on the instances you've created for the NM Template and the NM Atlas.

Let's start with the ParcellationEntityVersions (PEVs):

We follow an internal convention for PEV `"name"`, `"@id"`, `"lookupLabel"`, `"abbreviation"`, and `"alternateName"`:
- `"name"`: Stick to the name and capitalization actually used in the atlas data. I saw in your case that you do not capitalize in the atlas labels file (e.g. `"areas 1 and 2 of cortex"` not `"Areas 1 and 2 of cortex"`). Please see also my comment below about parent structures.
- `"abbreviation"`: Stick to the abbreviation you use in your atlas data (e.g. in file names). I think you are not providing them at all at this moment.
- `"lookupLabel"`: Should use the following convention ATLAS-ABBREVIATION_VERSION_AREA-NAME-LOWER-CAMEL-CASE (MNMA_v1.0_areas1And2OfCortex) or ATLAS-ABBREVIATION_VERSION_AREA-ABBREVIATION (MNMA_v1.0_A1-2). Alternatives for the atlas abbreviation: `"MNMA"`, `"MNMAtlas"`, `"MNM-atlas"`, `"MarmosetNMAtlas"`, etc.
- `"@id"`: Should be composed of "https://openminds.om-i.org/instances/parcellationEntityVersion/" + whatever you decide for the lookupLabel.
- `"alternateName"`: Has to be null or a list, even if this list only contains one alternate name. Alternate name can contain whatever name you have used for that PEV in any publication. In your current case this could be `["A1/2", "area 1 and 2"]` or `["A1/2", "area 1 and 2 of cortex"]` (depending on what you use as name).

PEVs should potentially be hierarchically structured by identifying their anatomical parent structure. Parent structures if not separately provided as annotation should be conceptually defined as ParcellationEntities (PEs). Identifying parent structures could also simplify naming of PEVs (not sure how flexible you are here in changing them still). For example: PEV `"MNMA_v1.0_areas1And2"` could identify PE `"MNMA_cortex"` as parent instead of implicitly mentioning the parent only in the PEV name as done right now (`"MNMA_v1.0_areas1And2OfCortex"`).

As AtlasAnnotations (AAs) you do provide multiple as far as I know:
1) probabilistic map (criteria type probabilistic)
2) maximum probability projection (criteria type deterministic)
3) surface map (at least for the cortical areas I assume) (criteria type deterministic ?)
This means that each PEV gets a list of at least 2 or 3 annotations. You identified laterality left and right for the current AA, this mean that left and right hemisphere of that area AA is present in the same file and that both have the same internal identifier in that file. Is this true for each AA? If not, you need to create an AA for each hemisphere with the corresponding internal identifier. 

Version identifier: you've stated "v1" so far which is fine if you only consider major updates in future. If minor updates are possible I would suggest to use "v1.0".

More feedback for the other instance types (parcellation entities, brain atlas, brain atlas version, etc) will follow shortly. I hope this helps already adapting your scripts :)

**Comment by baishi** [comment]
Hi @lzehl,

Apologise. I just realised that the issue tracker is not by default opened when I forked the project. I have enabled it.

However, I think it might be a good idea to leave the trace of documentation here in the main repository as reference when others want to contribute a new template.

As for PEV. I'll address each feedback below:
_1. "name": Stick to the name and capitalization actually used in the atlas data. I saw in your case that you do not capitalize in the atlas labels file (e.g. "areas 1 and 2 of cortex" not "Areas 1 and 2 of cortex"). Please see also my comment below about parent structures._

By saying atlas labels file, I assume you are referring to the metadata we uploaded to d-7b55dd29-c6f1-41b2-a886-64acb42036d7. So we follow the convention in the Marmoset community to name leaf nodes (structures provided as annotation) with starting smaller letter, and give the parent nodes not providing annotation capital starting letters. My understanding about this issue is mainly about the discrepancies between atlas_labels and the name I used in the jsonld file. Please correct me if I"m wrong.


_2. "abbreviation": Stick to the abbreviation you use in your atlas data (e.g. in file names). I think you are not providing them at all at this moment._

I followed examples of JBA and WHSSDatlas and none of them providing any "abbreviation". Instead they provide the abbreviation in the alternateName list and did not list the "name" in the alternateName list. So abbreviation is the preferred attribute instead of alternateName?

_3. "lookupLabel": Should use the following convention ATLAS-ABBREVIATION_VERSION_AREA-NAME-LOWER-CAMEL-CASE (MNMA_v1.0_areas1And2OfCortex) or ATLAS-ABBREVIATION_VERSION_AREA-ABBREVIATION (MNMA_v1.0_A1-2). Alternatives for the atlas abbreviation: "MNMA", "MNMAtlas", "MNM-atlas", "MarmosetNMAtlas", etc._

I will follow the MarmosetNMAtlas followed by area name lower camel case.

_4. "@id": Should be composed of "https://openminds.om-i.org/instances/parcellationEntityVersion/" + whatever you decide for the lookupLabel._

Will do.

_5. "alternateName": Has to be null or a list, even if this list only contains one alternate name. Alternate name can contain whatever name you have used for that PEV in any publication. In your current case this could be ["A1/2", "area 1 and 2"] or ["A1/2", "area 1 and 2 of cortex"] (depending on what you use as name)._

As mentioned above, I searched through AAL1 and WHSSD Atlas, and they neither list "name" again in the "alternateName" attribute.

For the

_PEVs should potentially be hierarchically structured by identifying their anatomical parent structure. Parent structures if not separately provided as annotation should be conceptually defined as ParcellationEntities (PEs). Identifying parent structures could also simplify naming of PEVs (not sure how flexible you are here in changing them still). For example: PEV "MNMA_v1.0_areas1And2" could identify PE "MNMA_cortex" as parent instead of implicitly mentioning the parent only in the PEV name as done right now ("MNMA_v1.0_areas1And2OfCortex")._

My understanding about this paragraph is
1. All nodes should be defined as PE
2. Only leaf nodes (provided as annotation) should has PEV. Branch nodes does not have versions
3. Mentioning of the parent should be done via "hasParent" attribute
4. hasParent should point to a PE, not a PEV
5. PEV may have hasParent attribute but all PE does not have hasParent attribute set

Please correct me if I'm not wrong and I missed out anything.

The AtlasAnnotations is too abstract and complicated. I think it would be more efficient to address during the conference call.

Lastly for the version identifier, the since the template was published we did not make any changes. There will be a version 2 in the foreseeable future, but once it is determined, it will not receive patches for a long period time. I think for the time being v1 and v2 would be good enough.

I'm working on the script to address all above. But please point out early if you can identify that I have misunderstood any part.

**Comment by lzehl** [comment]
@baishi we can keep the feedback here.

For the name: Please use the name in openMINDS PEV as you use it in your metadata files (so starting with small letters).

For the abbreviation: Please use the abbreviation in openMINDS PEV to provide the defined abbreviated name you use in your data/metadata. That the WHSSDatlas is not using this for their dedicated abbreviations is also not correct and should be corrected (@UlrikeS91 FYI). Not all atlases have dedicated abbreviations though. 

For alternateName: This is for any other name (abbreviated or not) that might be also okay for you to use but is not the official name or abbreviation. IT HAS TO BE A LIST (also with only one value). If you do not want to allow any other name but the official name and abbreviation please set this property to null.

For the PEV hierarchy here my feedback for your interpretation: 
- _All nodes should be defined as PE_
  - **YES** all leaf nodes or parent nodes should be defined as PE. 
- _Only leaf nodes (provided as annotation) should has PEV. Branch nodes does not have versions._
  - **NO** this is not universally true. This depends on your data and if the data only provide annotations for leaf nodes or also for parent nodes. Hypothetical example: you have a probability map (probabilistic annotation) for each cortex area (leaf nodes) but you also provide a probabilistic map for the whole cortex (parent node). In this case leaf nodes and parent nodes have PEs as well as PEVs. However if only the leaf nodes have annotations in your case, only the leaf nodes are represented as PEs and PEVs. All nodes with no annotation are only represented as PEs.
- _Mentioning of the parent should be done via "hasParent" attribute._ 
  - **YES** as linked types. NOTE: this also HAS TO BE A LIST. (cf. AAL1) 
- _hasParent should point to a PE, not a PEV_
  - **NO** this is not universally true (see also comment above). If parent has its own annotation it is represented twice as PE and as PEV. The leaf node of that parent should list the parent PEV and may also list the parent PE.
- _PEV may have hasParent attribute but all PE does not have hasParent attribute set_
  - **NO**. Both PEVs and PEs can have the hasParent attribute. Only difference is that PEVs can have a PE or a PEV as parent while PEs can only have PEs as parent.

We can discuss the annotation setting in our call. I also made a small mistake in my previous comment in this context which I corrected now.

Good for the version identifer. It is your decision. I just wanted to make sure.

**Comment by UlrikeS91** [comment]
> For the name: Please use the name in openMINDS PEV as you use it in your metadata files (so starting with small letters).

For the WHSSD atlas, we uncapitalized all region names - both annotated regions and hierarchical regions. Their hierarchical regions are capitalized and annotated regions are lowercase. The reason is that a region may have been annotated in an early version, but later used as the hierarchical term for subregions in later versions (and also because there are some mistakes in older versions, which would have become confusing). If I were to consider capitalization, I would have to add additional PEs and/or PEVs to capture this, which would be weird and partly even false in some cases since the combination of the new subregions may occupy the exact same voxels as the (now) hierarchical regions did. All relationships and version-specific details will be covered through connections in SANDS. 
1. PEs that do not have versions, have never been annotated themselves (purely hierarchical)
2. PEs that do have versions, have been annotated at some point or still annotated in the latest version; when they do not have versions in later versions of the atlas anymore, the region may have been "removed" or the regions has been annotated into subregions (i.e., the new subregions point to the PE as their parent); for WHSSD atlas this would typically mean that the internal ID of the region disappeared or was replaced by a new one in the MBAT file (i.e., from ID <1000 (reserved for annotated regions) to ID>1000 (reserved for hierarchical/not-annotated regions)) from one version to the next 

> For the abbreviation: Please use the abbreviation in openMINDS PEV to provide the defined abbreviated name you use in your data/metadata. That the WHSSDatlas is not using this for their dedicated abbreviations is also not correct and should be corrected ([@UlrikeS91](https://github.com/UlrikeS91) FYI). Not all atlases have dedicated abbreviations though.

Thank you. I'm in the process of reorganizing the entire WHSSD atlas representation. Due to EBRAINS needs back in time, some of the components in the representation had to be dropped in those first rounds. 

For WHSSD atlas, I will do the following for the terminology:

1. The regions from the label file (from ITK Snap) for a specific atlas versions will be the names of the PEVs for the BAV representation (linked as entities of the corresponding terminology version) and the names of the PEs for the entire BA representation
2. The additional regions from the MBAT file (which contains the entire terminology with hierarchy) for a specific atlas version will be the names of the PEs for the entire BA representation and the PEVs (and their corresponding PEs) from point 1 will point to them as their parents
3. Since WHSSD atlas has multiple versions and made a few changes to their terminologies over the years (both naming convention changes and new annotated (sub)regions), I will have to compare between versions to identify the entire terminology used by the atlas (version independently) and in some cases combine some regions into a single one (typically based on their internal identifiers (e.g., "anterior commissure, anterior part" was renamed to "anterior commissure, anterior limb" in v4 but ID remained the same)).
  - the PE will then get the latest name, and all older names will be added as alternate names
  - PEVs will keep their names of course (to perfectly reflect the ground-truth of the label file) and the other names will be added as alternate names
4. abbreviations will be handled similarly (although all of these are only stated in the MBAT file and not in the label file): PEVs receive the ones from their version as abbreviation, additional ones as alternate names; PEs receive the latest abbreviation and older ones as alternate names 
5. In some cases, I have also identified some errors in the names of brain regions, which will be corrected ("correctedName") but the ground-truth is still the name of the label file and should match the name of the PEV
6. Similarly, MBAT file is ground-truth for PE names but PE names are corrected in their PEV names immediately and the published names with the typo are added as alternate names

Everything that I am changing/correcting will be described as additional remarks so that it is clear what happened and why. 

Overview for WHSSD atlas: 
LABEL file = ground-truth 
MBAT file = ground-truth for some SANDS properties (but LABEL file trumps MBAT file for shared content)

PEV property | origin in WHSSD atlas version
-- | --
name | region name from LABEL file (uncapitalized if necessary)
abbreviation | abbreviation from MBAT file (exact, with capitalization)
additionalRemarks | combination of description from MBAT file and my own changes/corrections/comments
alternateName | region name and/or abbreviations from MBAT and/or LABEL file from other atlas versions
correctedName | corrected PEV name (sometimes corresponds to MBAT file name (with its description stating that the error has been corrected there; sometimes identified by me and not noticed by the atlas providers before)
hasParent | PEs (exact reflection of hierarchy in MBAT file; WHSSD atlas has no annotated regions as parent structures, therefore never another PEV within the same atlas version (but linked PE may have versions that typically are part of previous atlas versions))
   
PE property | origin in WHSSD atlas version
-- | --
name | name or correctName of PEVs and region name of MBAT files for hierarchical regions (uncapitalized if necessary; PEs with multiple versions with different names get name from latest version)
abbreviation | abbreviation from MBAT file (exact, with capitalization; PEs with multiple versions with different abbreviations get abbreviation from latest version)
alternateName | region name and/or abbreviations from MBAT and/or LABEL file from other atlas versions
hasParent | PEs (exact reflection of hierarchy in MBAT files)

**Comment by UlrikeS91** [comment]
> Hi [@UlrikeS91](https://github.com/UlrikeS91),
> 
> Can you confirm one thing? For the WHSSDatlas, PE, the latest one on github (rev 841c44) does not have any hasParent set, a grep shows all hasParent are set to null.
> 
> I can comprehend most of your information above. But when I apply it to real examples, I sometimes get confused.

Yes, that is correct. We are lacking the hierarchy representation at the moment. That was also one of the components that we had to drop in those first rounds.

**Comment by baishi** [comment]
Hi @lzehl ,

We have updated the instances repository https://github.com/Neuroinflab/openMINDS_instances/tree/MarmosetNM_Atlas with the capitalisation suggestions, alternateName of list instead of string, hasParent and abbreviation property.

Please kindly have a cross check if that is more organised by now.

**Comment by baishi** [comment]
Hi, @lzehl ,

Apologies, there was a typo in the toCamelCase function which screwed up the first letter of the id.

Also you are absolutely right, my script accidentally overwrote the id by its parent id, thus repeated giving the jsonld file a wrong file name.

I have fixed both and it should look much better by now.

Would you give it another sight please?

**Comment by lzehl** [comment]
@baishi :) 

I had a second look now. Here some more comments (sorry for doing this step wise but I only have small free time slots at the moment):

It is up to you, but I would not list the lowerCamelCase variant in the alternate name (I would only keep this if you are actually using this elsewhere than for the openMINDS lookupLabel). You should also not repeat the already stated name and abbreviation in the alternateName list. As the property name suggests: this should be alternatives to the already stated options. If this is done elsewhere this needs to be corrected as well (@UlrikeS91 FYI). This is true for all PEVs and all PEs.

For the BrainAtlasVersion `"https://doi.org/10.1016/j.neuroimage.2020.117625"` is the DOI of the research paper. For me this is a poor identifier of the atlas version (because it is not a digital identifier for the underlying data). We can discuss this. This should maybe be replaced with the EBRAINS DOI (once this is published). I would list the research paper DOI under:
```
    "relatedPublication": [
        {
            "@id": "https://doi.org/10.1016/j.neuroimage.2020.117625"
        }
    ],
```

I would optimize the BrainAtlas(Version) full name, short name, and description. This is too focused on the template but you are presenting here the atlas. Suggestion (please further optimize and correct in particular the description): 
```
    "fullName": "Marmoset Nencki-Monash Probabilistic Cytoarchitectonic Brain Atlas",
```
```
    "shortName": "Marmoset Nencki-Monash Atlas",
```
```
    "abbreviation": "MarmosetNMA",
```
```
    "description": "The Marmoset Nencki-Monash Atlas is a three dimensional (3D) probabilistic  brain atlas reconstructed from 20 young adult marmoset monkeys (Callithrix jacchus) and segmented based on the cytoarchitectonic analysis of the serial Nissl-stained sections of those brains. EXPAND-IF-YOU-WANT",
```

Respectively I would suggest the following for the CommonCoordinateSpaceVersion (please further optimize and correct in particular the description; instead of "template" you could also use "model" or "space"; However I would not use "template" for the atlas):
```
    "fullName": "Marmoset Nencki-Monash Population-Based Brain Template",
```
```
    "shortName": "Marmoset Nencki-Monash Template",
```
```
    "abbreviation": "MarmosetNMT",
```
```
    "description": "The Marmoset Nencki-Monash Template is a three dimensional (3D) population-based  brain template reconstructed from 20 postmortem brains obtained from young adult marmoset monkeys (Callithrix jacchus). EXPAND-IF-YOU-WANT",
```
(Please change lookupLabels and atIds accordingly)

For all properties that you do not provide a value for, please set them to null (not empty lists or empty strings).

As far as I understand you are not providing a deterministic brain atlas but one that is based on averages of a small population (20 different monkeys). So you are providing a probabilistic atlas (please change the atlas type). A maximum probability map is just a deterministic projection of a probabilistic map.

I can't do more for now but I hope this helps again to get you one step closer.

**Comment by baishi** [comment]
Hi @lzehl ,

Thanks for the input. I have done updates:

1. removed camelCase name, full name and short code from alternateName
2. the doi is revised to EBRAINS Knowledge Graph https://search.kg.ebrains.eu/instances/6eb874e1-63b3-4889-948a-0d3987cb249b data is pending curation. Please let me know if the url format for KG is correct.
3. updated relatedPublication
4. I have put up your suggestions for short name and full name. Piotr will make the final vetting of the names.
5. removed empty string properties
6. updated atlas type and annotation type to probabilistic
7. fixed several other typos in names and species used etc.

No worry for the stepped comments. Any small step is one step closer to a proper upload.

**Comment by lzehl** [comment]
@baishi we are getting close :)

Here some more things:

`"https://search.kg.ebrains.eu/instances/6eb874e1-63b3-4889-948a-0d3987cb249b"` would not go under digital identifier, this would just be a placeholder for now until you receive a DOI for the KG dataset entry.

`"https://openminds.om-i.org/instances/parcellationEntity/MarmosetNMA_areas_1And_2OfCortex"` this is still not correctly formatted. Should be 
`"https://openminds.om-i.org/instances/parcellationEntity/MarmosetNMA_areas1And2OfCortex"`. There should be no `"_"` between `"area"` and the `"XXOfCortex"`. This issue reoccurs in the filenames and lookupLabels for parcellation entities. And it is also still an issue for the parcellation entity versions.

I need to clarify if `"Histology\u2010Based"` is okay or if this should be `"Histology-Based"`.

Filename, abbreviation, and atid of common coordinate space (version) is not correct. Currently uses `"MarmosetNMA"` should be `"MarmosetNMT"` or something else, but not the same as the atlas.

Please provide "howToCite", "axisOrigin", "digitalIdentifier", and "releaseDate" (if available)  for the common coordinate space version.

`"alternateName": [],` should be null if not specified -> `"alternateName": null,`

Atlas annotations we are going to discuss in person.

**Comment by lzehl** [comment]
For the atlas annotations within the parcellation entity versions, here an example how this could/should look like:
```

{
    "@context": {
        "@vocab": "https://openminds.om-i.org/props/"
    },
    "@type": "https://openminds.om-i.org/types/ParcellationEntityVersion",
    "abbreviation": "A11",
    "alternateName": null,
    "hasParent": [
        {
            "@id": "https://openminds.om-i.org/instances/parcellationEntity/MarmosetNMA_orbitalFrontalCortex"
        }
    ],
    "name": "area 11 of cortex",
    "ontologyIdentifier": null,
    "@id": "https://openminds.om-i.org/instances/parcellationEntityVersion/MarmosetNMA_v1_area11OfCortex",
    "lookupLabel": "MarmosetNMA_v1_area11OfCortex",
    "additionalRemarks": null,
    "correctedName": null,
    "hasAnnotation": [
        {
            "@type": "https://openminds.om-i.org/types/AtlasAnnotation",
            "anchorPoint": null,
            "criteria": null,
            "criteriaQualityType": {
                "@id": "https://openminds.om-i.org/instances/criteriaQualityType/processive"
            },
            "criteriaType": {
                "@id": "https://openminds.om-i.org/instances/annotationCriteriaType/probabalisticAnnotation"
            },
            "inspiredBy": null,
            "internalIdentifier": "3",
            "laterality": [
                {
                    "@id": "https://openminds.om-i.org/instances/laterality/left"
                }
            ],
            "preferredVisualization": {
                "@type": "https://openminds.om-i.org/types/ViewerSpecification",
                "additionalRemarks": null,
                "anchorPoint": null,
                "cameraPosition": null,
                "preferredDisplayColor": null,
            },
            "specification": null,
            "type":   {
                "@id": "https://openminds.om-i.org/instances/annotationType/annotationMask"
            }
        },
        {
            "@type": "https://openminds.om-i.org/types/AtlasAnnotation",
            "anchorPoint": null,
            "criteria": null,
            "criteriaQualityType": {
                "@id": "https://openminds.om-i.org/instances/criteriaQualityType/processive"
            },
            "criteriaType": {
                "@id": "https://openminds.om-i.org/instances/annotationCriteriaType/deterministicAnnotation"
            },
            "inspiredBy": null,
            "internalIdentifier": null,
            "laterality": [
                {
                    "@id": "https://openminds.om-i.org/instances/laterality/left"
                }
            ],
            "preferredVisualization": {
                "@type": "https://openminds.om-i.org/types/ViewerSpecification",
                "additionalRemarks": null,
                "anchorPoint": null,
                "cameraPosition": null,
                "preferredDisplayColor": {
                    "@id": "https://openminds.om-i.org/instances/singleColor/#E9BF3B"
                }
            },
            "specification": null,
            "type":  {
                "@id": "https://openminds.om-i.org/instances/annotationType/annotationMask"
            }
        }
    ],
    "relationAssessment": null,
    "versionIdentifier": "v1",
    "versionInnovation": null
}
```

For annotation type: Not sure if annotation mask is correct for your probability and maximum probability maps. Here is the full list of possible values we have for now: https://openminds-documentation.readthedocs.io/en/latest/instance_libraries/terminologies/annotationType.html
Let us know if something is missing.

For the preferred visualization: I deleted the single color from the probabalistic annotation, because I would assume that this should rather be a color map reflecting the probability of that area being at that spatial point (voxel?). Here are all currently registered color maps (please let us know if something is missing): https://openminds-documentation.readthedocs.io/en/latest/instance_libraries/terminologies/colormap.html

For the internal identifier: I set the one for the deterministic one to null because I did not know if this is the same as for the probabalisic one. Please provide whatever is correct here.

Let me know if you have questions :)

**Comment by baishi** [comment]
> "https://search.kg.ebrains.eu/instances/6eb874e1-63b3-4889-948a-0d3987cb249b" would not go under digital identifier, this would just be a placeholder for now until you receive a DOI for the KG dataset entry.
Noted. I'll keep it there and wait for publish of the dataset.

> "https://openminds.om-i.org/instances/parcellationEntity/MarmosetNMA_areas_1And_2OfCortex" this is still not correctly formatted. Should be "https://openminds.om-i.org/instances/parcellationEntity/MarmosetNMA_areas1And2OfCortex". There should be no "_" between "area" and the "XXOfCortex". This issue reoccurs in the filenames and lookupLabels for parcellation entities. And it is also still an issue for the parcellation entity versions.
It is all revised and all extra underscores are removed.

> I need to clarify if "Histology\u2010Based" is okay or if this should be "Histology-Based".
Yes it should be Histology-Based. The \u2010 is actually what I copied from github, the message above provided by you.

> Filename, abbreviation, and atid of common coordinate space (version) is not correct. Currently uses "MarmosetNMA" should be "MarmosetNMT" or something else, but not the same as the atlas.
This is done. All to MarmosetNMT
 
> Please provide "howToCite", "axisOrigin", "digitalIdentifier", and "releaseDate" (if available) for the common coordinate space version.
I have put up axesOrigin and the other fields I will leave for the next update.

> "alternateName": [], should be null if not specified -> "alternateName": null
This is done

**Comment by baishi** [comment]
Hi @lzehl ,

I have updated the git repo of the hasAnnotation property, following your advice:

>For annotation type: Not sure if annotation mask is correct for your probability and maximum probability maps. Here is the full list of possible values we have for now: https://openminds-documentation.readthedocs.io/en/latest/instance_libraries/terminologies/annotationType.html
Let us know if something is missing.

The annotationMask is closest, so I put it there first.

>For the preferred visualization: I deleted the single color from the probabalistic annotation, because I would assume that this should rather be a color map reflecting the probability of that area being at that spatial point (voxel?). Here are all currently registered color maps (please let us know if something is missing): https://openminds-documentation.readthedocs.io/en/latest/instance_libraries/terminologies/colormap.html

Could you advice the usage of colormap? I tried to find an example from the current instances but could not find any. I put it as @id and set it to grayscale. Please let correct me if I'm wrong.

>For the internal identifier: I set the one for the deterministic one to null because I did not know if this is the same as for the probabalisic one. Please provide whatever is correct here.

We use the same identifier for the same area throughout. So I put it the same at the moment.

**Comment by lzehl** [comment]
I believe this issue was solved with closing the following PRs:
https://github.com/openMetadataInitiative/openMINDS_instances/pull/303
https://github.com/openMetadataInitiative/openMINDS_instances/pull/341
https://github.com/openMetadataInitiative/openMINDS_instances/pull/345
